config/routes.rb
Rails.application.routes.draw do
  root "trails#index"
  resources :people do
    resources :practices, only: %i[new create update]
    resources :runs, only: %i[show new create update]
  end
  resources :trails do
    get "eligible-people", to: "trails#eligibles", on: :member
    resources :races do
      put "finish", to: "races#finish", on: :member
    end
  end

  get "races", to: "races#all"
end

app/models/person.rb
class Person < ApplicationRecord
  enum body_build: {
    SLIM: 0,
    FIT: 1,
    LARGE: 2
  }, _prefix: true

  has_many :practices, dependent: :destroy
  has_many :trails, through: :practices
  has_many :runs, dependent: :destroy
  has_many :races, through: :runs

  validates :name, presence: true
  validates :birthdate, presence: true
  validates :weight, presence: true
  validates :body_build, presence: true

  def name
    self[:name].titleize if self[:name].present?
  end

  def age
    ((Time.zone.now - birthdate.to_time) / 1.year.seconds).floor
  end

  def ongoing_practice?
    ongoing_practice.present?
  end

  def ongoing_practice
    practices.where(status: :STARTED).first
  end

  def past_practices?
    past_practices.present?
  end

  def past_practices
    practices.where(status: :FINISHED)
  end

  def practice_on?(trail)
    !ongoing_practice? && trail.eligible?(age, weight, body_build)
  end

  def ongoing_race?
    ongoing_race.present?
  end

  def ongoing_race
    races.where('"races"."status" = 1 AND "runs"."status" = 0').first
  end

  def finished_practice_on?(trail_id)
    past_practices.where(trail_id: trail_id).present?
  end

  def registered_runs
    runs.where(status: :REGISTERED)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, except: %i[index new create]

  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    redirect_to @person and return if @person.save

    render :new, status: :unprocessable_entity
  end

  def edit
  end

  def update
    redirect_to @person and return if @person.update(person_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @person.destroy
    redirect_to people_path, status: :see_other
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :birthdate, :weight, :body_build)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with model: person do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% person.errors.full_messages_for(:name).each do |message| %>
      <div class="form_error"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :birthdate %>
    <%= form.date_field :birthdate %>
    <% person.errors.full_messages_for(:birthdate).each do |message| %>
      <div class="form_error"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :weight %>
    <%= form.number_field :weight %>
    <% person.errors.full_messages_for(:weight).each do |message| %>
      <div class="form_error"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body_build %>
    <%= form.radio_button :body_build, 'SLIM' %>
    <%= form.label :body_build, 'SLIM' %><br>
    <%= form.radio_button :body_build, 'FIT' %>
    <%= form.label :body_build, 'FIT' %><br>
    <%= form.radio_button :body_build, 'LARGE' %>
    <%= form.label :body_build, 'LARGE' %><br>

    <% person.errors.full_messages_for(:body_build).each do |message| %>
      <div class="form_error"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h3>Edit Person</h3>

<%= render "form", person: @person %>

app/views/people/index.html.erb
<div class="row">
  <div class="column_left">
    <h3>People using Trails</h3>
  </div>
  <div class="column_right">
    <%= button_to "New Person", new_person_path, method: :get %>
  </div>
</div>

<article class="cards">
<% @people.each do |person| %>
  <article class="card">
    <%= image_tag("user.png")%> <%= link_to person.name, person %>
  </article>
<% end %>
</article>

app/views/people/new.html.erb
<h3>New Person</h3>

<%= render "form", person: @person %>

app/views/people/show.html.erb
<h3><%= image_tag("user_32.png")%> <%= @person.name %>'s Page</h3>
<article>
<h4>Details</h4>
<p>
Age: <b><%= @person.age %></b> <br>
Birthdate: <b><%= @person.birthdate %></b> <br>
Weight: <b><%= @person.weight %> kg</b> <br>
Body Build: <b><%= @person.body_build %></b>
</p>

<%= link_to "Edit", edit_person_path(@person) %> | 
<%= link_to "Remove", person_path(@person), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
</article>
<article>
<h4>Trail History</h4>
<% if @person.ongoing_practice? %> 
  <article>
    <div class="row">
      <div class=column_left>
        <strong><%= @person.ongoing_practice.trail.name %></strong>
        <%= status_tag('ONGOING') %><br>
        <%= link_to "Details", @person.ongoing_practice.trail %>
      </div>
      <div class=column_right>
        <%= form_with model: [@person, @person.ongoing_practice] do |form| %>
          <%= form.hidden_field :status, value: :FINISHED %>
          <%= form.submit "Finish Practice"%>
        <% end %>
      </div>
    </div>
    <% if flash[:alert] %>
      <div class="form_error"><%= flash[:alert] %></div>
    <% end %>
  </article>
<% else %> 
  <p> No ongoing trails at the moment. <%= link_to "Start Practice on a Trail!", new_person_practice_path(@person) %> </p>
<% end %> 

<details>
<summary>Past Trails</summary>
<% if @person.past_practices? %> 
  <ul>
  <% @person.past_practices.each do |practice| %> 
    <li><%= link_to practice.trail.name, practice.trail %> (<%= practice.updated_at.strftime("%Y-%m-%d %I:%M%p") %>)</li> 
  <% end %> 
  </ul>
<% else %> 
  None yet!
<% end %>
</details>
</article>

<article>
<h4>Race History</h4>
<%= link_to "Register for a Race", new_person_run_path(@person) %></td>
<ul>
<% @person.runs.each do |run| %> 
  <li><%= link_to run.race.name, person_run_path(@person, run) %></li>
<% end %> 
</ul>
</article>