config/routes.rb
Rails.application.routes.draw do
  root "trails#index"
  resources :people do
    resources :practices, only: %i[new create update]
    resources :runs, only: %i[show new create update]
  end
  resources :trails do
    get "eligible-people", to: "trails#eligibles", on: :member
    resources :races do
      put "finish", to: "races#finish", on: :member
    end
  end

  get "races", to: "races#all"
end

app/models/race.rb
class Race < ApplicationRecord
  enum status: {
    NEW: 0,
    STARTED: 1,
    FINISHED: 2
  }, _prefix: true

  belongs_to :trail

  has_many :runs, dependent: :destroy
  has_many :people, through: :runs

  validates :name, presence: true
  validates :start, presence: true
  validates :duration, presence: true
  validate :detail_change_allowed, on: :update, unless: :status_changed?
  validate :time_overlaps, if: :start_changed? || :duration_changed?
  validate :status_change, on: :update, if: :status_changed?

  before_validation :start_time_cleanup, on: :create

  def name
    self[:name].titleize if self[:name].present?
  end

  def expected_end
    start + duration.hours
  end

  def registered_runs
    runs.where(status: %i[REGISTERED FINISHED UNFINISHED]).order(:duration)
  end

  def no_overlaps_within_trail?(trail_id, tentative_start, tentative_duration)
    tentative_end = tentative_start + tentative_duration.hours
    overlaps = Race.where("trail_id = ? AND (start, duration * INTERVAL '1 hour') OVERLAPS (?, ? * INTERVAL '1 hour')", trail_id, tentative_start, tentative_duration)
    overlaps.blank? || (overlaps.length == 1 && overlaps.first.id == id)
  end

  def overlaps?(tentative_start, tentative_duration)
    tentative_end = tentative_start + tentative_duration.hours
    (start < tentative_end) && (tentative_start < expected_end)
  end

  private
  def start_time_cleanup
    self[:start] = self[:start].change(sec: 0) if self[:start].present?
  end

  def detail_change_allowed
    return if registered_runs.blank?

    errors.add(:detail, 'changes no longer allowed')
  end

  def time_overlaps
    return if no_overlaps_within_trail?(trail_id, start.to_datetime, duration.to_i)

    errors.add(:time_period, 'overlaps another race in the same trail')
  end

  def status_change
    return if !status_STARTED?

    return if registered_runs.length > 1

    errors.add(:status, 'Cannot start with less than 2 participants')
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  prepend_before_action :set_trail, except: %i[all]
  before_action :set_race, except: %i[index new create all]

  def index
    @races = @trail.races
  end

  def show
    return if !@race.winner.present?

    @winning_run = Run.find(@race.winner)
    @winner = @winning_run.person
  end

  def new
    @race = Race.new
  end

  def create
    @race = @trail.races.create(race_params)

    redirect_to trail_race_path(@trail, @race) and return if @race.errors.blank?

    render :new, status: :unprocessable_entity
  end

  def edit
  end

  def update
    redirect_to trail_race_path(@trail, @race) and return if @race.update(race_params)

    render :edit, status: :unprocessable_entity and return if !@race.errors.include?(:status)

    flash[:alert] = @race.errors.messages_for(:status).first
    redirect_to trail_race_path(@trail, @race)
  end

  def destroy
    @race.destroy
    redirect_to trail_races_path(@trail), status: :see_other
  end

  def all
    filter = {}
    filter[:trail_id] = races_params[:trail_id] if races_params[:trail_id].present?
    filter[:status] = races_params[:status] if races_params[:status].present?
    @races = Race.all.where(filter).order(start: :desc)
  end

  def finish
    update_race_response = RaceFinisher.call(@race, true)

    redirect_to trail_race_path(@trail, @race) and return if update_race_response[:result]

    flash[:alert] = update_race_response[:message]
    redirect_to trail_race_path(@trail, @race)
  end

  private

  def set_trail
    @trail = Trail.find(params[:trail_id])
  end

  def set_race
    @race = Race.find(params[:id])
  end

  def race_params
    params.require(:race).permit(:name, :duration, :start, :status)
  end

  def races_params
    params.permit(:status, :trail_id)
  end
end

app/helpers/races_helper.rb
module RacesHelper
  def participant_line(run)
    participant_line = "#{run.person.name}"
    participant_line += " (#{run.duration}h)" if run.duration

    "<li>#{participant_line}</li>".html_safe
  end
end

app/views/races/_form.html.erb
<%= form_with model: [@trail, @race] do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% @race.errors.full_messages_for(:name).each do |message| %>
      <div class="form_error"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label 'Start Date and Time' %>
    <%= form.datetime_local_field :start %>
    <% @race.errors.full_messages_for(:start).each do |message| %>
      <div class="form_error"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :duration %>
    <%= form.number_field :duration, step: 0.01 %>
    <% @race.errors.full_messages_for(:duration).each do |message| %>
      <div class="form_error"><%= message %></div>
    <% end %>
  </div>

  <% @race.errors.full_messages_for(:detail).each do |message| %>
    <div class="form_error"><%= message %></div>
  <% end %>
  <% @race.errors.full_messages_for(:status).each do |message| %>
    <div class="form_error"><%= message %></div>
  <% end %>
  <% @race.errors.full_messages_for(:time_period).each do |message| %>
    <div class="form_error"><%= message %></div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to "Back to Races", trail_races_path(@trail) %>

app/views/races/all.html.erb
<h3>List of Races</h3>

<div class="row">
  <div class="side_left">
    <h5>Filter</h5>
    <%= form_with path: races_path, method: :get do |form| %>
      <%= form.label "Trail" %>
      <%= form.select :trail_id, Trail.all.collect {|trail| [trail.name, trail.id]}, include_blank: true %> <br>
      <%= form.label "Status" %>
      <%= form.select :status, Race.statuses.collect, include_blank: true %> <br>
      <%= form.submit "Filter"%>
    <% end %>

  </div>

  <div class="side_right">
    <table>
      <thead>
        <tr>
          <th>Race Name</th>
          <th>Status</th>
          <th>Start Date</th>
          <th>Start Time</th>
        </tr>
      </thead>
      <tbody>
        <% @races.each do |race| %>
        <tr>
          <td>
            <%= image_tag("race.png")%> 
            <%= link_to race.name, [race.trail, race] %><br>
            <i><%= race.trail.name %> Trail</i>
          </td>
          <td><%= status_tag(race.status) %></td>
          <td><%= race.start.to_date %></td>
          <td><%= race.start.strftime("%I:%M%p") %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/races/edit.html.erb
<h3>Edit Race Details</h3>

<%= render "form", race: @race %>

app/views/races/index.html.erb
<h3><%= image_tag("trail_32.png")%> The <%= @trail.name %> Trail</h3>

<div class="row">
  <div class="column_left">
    <h3>List of Races</h3>
  </div>
  <div class="column_right">
    <%= button_to "New Race", new_trail_race_path, method: :get %>
  </div>
</div>

<% if @races.present? %>
<table>
  <thead>
    <tr>
      <th>Race Name</th>
      <th>Status</th>
      <th>Start Date</th>
      <th>Start Time</th>
    </tr>
  </thead>
<tbody>
  <% @races.order(:start).each do |race| %>
  <tr>
    <td><%= image_tag("race.png")%> <%= link_to race.name, [@trail, race] %></td>
    <td><%= status_tag(race.status) %></td>
    <td><%= race.start.to_date %></td>
    <td><%= race.start.strftime("%I:%M%p") %></td>
  </tr>
  <% end %>
</tbody>
</table>
<% else %>
<p>None yet!</p>
<% end %>

<%= link_to "Back", trail_path(@trail) %>

app/views/races/new.html.erb
<h3>New Race Details</h3>

<%= render "form", race: @race %>

app/views/races/show.html.erb
<h3><%= image_tag("race_32.png")%> The <%= @race.name %> Race</h3>

<% if @race.status_NEW? %>
  <%= form_with model: [@trail, @race] do |form| %>
    <%= form.hidden_field :status, value: :STARTED %>
    <%= form.submit "Start Race"%>
  <% end %>
<% end %>

<% if @race.status_STARTED? %>
  <%= button_to "Finish Race", finish_trail_race_path(@trail, @race), method: "put" %>
<% end %>

<% if flash[:alert] %>
  <div class="form_error"><%= flash[:alert] %></div>
<% end %>

<article>
<h4>Details</h4>
<p>
Trail: <%= link_to @race.trail.name, trail_path(@race.trail) %> <br>
Status: <b><%= status_tag(@race.status) %> <br></b>
Start Date: <b><%= @race.start.to_date %></b> <br>
Start Time: <b><%= @race.start.strftime("%I:%M%p") %></b> <br>
End Date: <b><%= @race.expected_end.to_date %></b> <br>
End Time: <b><%= @race.expected_end.strftime("%I:%M%p") %></b> <br>
Duration (hours): <b><%= @race.duration %></b>
</p>
<%= link_to "Edit Details", edit_trail_race_path([@trail, @race]) %> | 
<%= link_to "Remove", trail_race_path([@trail, @race]), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
</article>

<article>
<% if @race.winner.present? %>
  <h4>Winner</h4>
  Runner #<%= @winning_run.id %>: <%= @winner.name %> (<%= @winning_run.duration %>h)
<% end %>
<h4>Participants</h4>
<% if @race.registered_runs.present? %> 
  <ol>
  <% @race.registered_runs.each do |run| %> 
    <%= participant_line(run) %>
  <% end %> 
  </ol>
<% else %> 
  None yet!
<% end %> 
</article>