config/routes.rb
Rails.application.routes.draw do
  root "trails#index"
  resources :people do
    resources :practices, only: %i[new create update]
    resources :runs, only: %i[show new create update]
  end
  resources :trails do
    get "eligible-people", to: "trails#eligibles", on: :member
    resources :races do
      put "finish", to: "races#finish", on: :member
    end
  end

  get "races", to: "races#all"
end

app/models/trail.rb
class Trail < ApplicationRecord
  enum body_build: Person.body_builds

  has_many :practices, dependent: :destroy
  has_many :people, through: :practices
  has_many :races, dependent: :destroy

  validates :name, presence: true

  def name
    self[:name].titleize if self[:name].present?
  end

  def eligible?(age, weight, person_body_build)
    age_eligible(age) && weight_eligible(weight) && body_build_eligible(person_body_build)
  end

  def ongoing_practices?
    ongoing_practices.present?
  end

  def ongoing_practices
    practices.where(status: :STARTED)
  end

  def past_practices?
    past_practices.present?
  end

  def past_practices
    finished_practices = practices.where(status: :FINISHED)
    finished_practices.uniq { |item| [item.person_id] }
  end

  def upcoming_races
    races.where(status: :NEW).order(:start)
  end

  def ongoing_race
    races.where(status: :STARTED).first
  end

  private

  def age_eligible(age)
    lower_pass = !(age_minimum && age < age_minimum)
    upper_pass = !(age_maximum && age > age_maximum)
    lower_pass && upper_pass
  end

  def weight_eligible(weight)
    lower_pass = !(weight_minimum && weight < weight_minimum)
    upper_pass = !(weight_maximum && weight > weight_maximum)
    lower_pass && upper_pass
  end

  def body_build_eligible(person_body_build)
    body_build.blank? || person_body_build == body_build
  end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  before_action :set_trail, except: %i[index new create]

  def index
    @trails = Trail.all
  end

  def show
  end

  def new
    @trail = Trail.new
  end

  def create
    @trail = Trail.new(trail_params)

    redirect_to @trail and return if @trail.save

    render :new, status: :unprocessable_entity
  end

  def edit
  end

  def update
    redirect_to @trail and return if @trail.update(trail_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @trail.destroy
    redirect_to trails_path, status: :see_other
  end

  def eligibles
    @eligible_people = EligiblesFinder.call(@trail)
  end

  private

  def set_trail
    @trail = Trail.find(params[:id])
  end

  def trail_params
    params.require(:trail).permit(:name, :age_minimum, :age_maximum, :body_build, :weight_minimum, :weight_maximum)
  end
end

app/helpers/trails_helper.rb
module TrailsHelper
  def age_criteria_line(trail)
    line = case [trail.age_minimum.present?, trail.age_maximum.present?]
             when [false, false]
               'Any'
             when [false, true]
               "Up to #{trail.age_maximum}"
             when [true, false]
               "At least #{trail.age_minimum}"
             when [true, true]
               "#{trail.age_minimum} to #{trail.age_maximum}"
           end
    line.html_safe
  end

  def weight_criteria_line(trail)
    line = case [trail.weight_minimum.present?, trail.weight_maximum.present?]
             when [false, false]
               'Any'
             when [false, true]
               "Up to #{trail.weight_maximum}"
             when [true, false]
               "At least #{trail.weight_minimum}"
             when [true, true]
               "#{trail.weight_minimum} to #{trail.weight_maximum}"
           end
    line.html_safe
  end

  def body_build_criteria_line(trail)
    line = trail.body_build || 'Any'
    line.html_safe
  end
end

app/views/trails/_form.html.erb
<%= form_with model: trail do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% trail.errors.full_messages_for(:name).each do |message| %>
      <div class="form_error"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label 'Minimum Age' %>
    <%= form.number_field :age_minimum %>
    <%= form.label 'Maximum Age' %>
    <%= form.number_field :age_maximum %>
  </div>

  <div>
    <%= form.label 'Minimum Weight (kg)' %>
    <%= form.number_field :weight_minimum %>
    <%= form.label 'Maximum weight (kg)' %>
    <%= form.number_field :weight_maximum %>
  </div>

  <div>
    <%= form.label :body_build %>
    <%= form.radio_button :body_build, 'SLIM' %>
    <%= form.label :body_build, 'SLIM' %> <br>
    <%= form.radio_button :body_build, 'FIT' %>
    <%= form.label :body_build, 'FIT' %> <br>
    <%= form.radio_button :body_build, 'LARGE' %>
    <%= form.label :body_build, 'LARGE' %> <br>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trails/edit.html.erb
<h3>Edit Trail</h3>

<%= render "form", trail: @trail %>

app/views/trails/eligibles.html.erb
<h3>People eligible for the <%= @trail.name %> Trail</h3>
<article class="cards">
<% @eligible_people.each do |person| %>
  <article class="card">
    <%= image_tag("user.png")%> <%= link_to person.name, person %>
  </article>
<% end %>
</article>

<%= link_to "Back", trail_path(@trail) %>

app/views/trails/index.html.erb
<div class="row">
  <div class="column_left">
    <h3>List of Trails</h3>
  </div>
  <div class="column_right">
    <%= button_to "New Trail", new_trail_path, method: :get %>
  </div>
</div>

<article class="cards">
<% @trails.each do |trail| %>
  <article class="card">
    <%= image_tag("trail.png")%> <%= link_to trail.name, trail %>
  </article>
<% end %>
</article>

app/views/trails/new.html.erb
<h3>New Trail</h3>

<%= render "form", trail: @trail %>

app/views/trails/show.html.erb
<h3><%= image_tag("trail_32.png")%> The <%= @trail.name %> Trail</h3>

<article>
<h4>Requirements:</h4>
<p>
Age (years): <%= age_criteria_line(@trail) %> <br>
Weight (kg): <%= weight_criteria_line(@trail) %> <br>
Body Build: <%= body_build_criteria_line(@trail) %>
</p>

<%= link_to "Edit", edit_trail_path(@trail) %> |
<%= link_to "Remove", trail_path(@trail), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

</article>

<article>
<% if @trail.ongoing_race.present? %>
  <h4>Ongoing Race</h4>
  <%= link_to @trail.ongoing_race.name, [@trail, @trail.ongoing_race] %> - <%= @trail.ongoing_race.start.to_date %>, <%= @trail.ongoing_race.start.strftime("%I:%M%p") %>
<% end %>

<h4>Upcoming Race</h4>
<% if @trail.upcoming_races.present? %>
  <ul>
    <% @trail.upcoming_races.each do |race| %>
    <li>
      <%= link_to race.name, [@trail, race] %> - <%= race.start.to_date %>, <%= race.start.strftime("%I:%M%p") %>
    </li>
    <% end %>
  </ul>
<% else %>
  <p>None at the moment.</p> 
<% end %>
<%= link_to "See All Races", trail_races_path(@trail) %>
</article>

<article>
<h4>Ongoing Trailers</h4>
<% if @trail.ongoing_practices? %> 
  <ul>
  <% @trail.ongoing_practices.each do |practice| %> 
    <li><%= link_to practice.person.name, practice.person %> </li>
  <% end %> 
  </ul>
<% else %> 
  <p>None at the moment.</p> 
<% end %> 
<%= link_to "See Eligibles", eligible_people_trail_path(@trail) %>

<h4>Trail Finishers</h4>
<% if @trail.past_practices? %> 
  <ul>
  <% @trail.past_practices.each do |practice| %> 
    <li><%= link_to practice.person.name, practice.person %> </li>
  <% end %> 
  </ul>
<% else %> 
  None yet!
<% end %> 