config/routes.rb
Rails.application.routes.draw do
  root "trails#index"
  resources :people do
    resources :practices, only: %i[new create update]
    resources :runs, only: %i[show new create update]
  end
  resources :trails do
    get "eligible-people", to: "trails#eligibles", on: :member
    resources :races do
      put "finish", to: "races#finish", on: :member
    end
  end

  get "races", to: "races#all"
end

app/models/run.rb
class Run < ApplicationRecord
  enum status: {
    REGISTERED: 0,
    DROPPED: 1,
    FINISHED: 2,
    UNFINISHED: 3
  }, _prefix: true

  belongs_to :person
  belongs_to :race

  validates :person_id, uniqueness: {
    scope: :race_id,
    message: 'already registered for this race'
  }
  validate :person_availability, on: :create
  validate :person_eligibility, on: :create
  validate :race_ongoing_registration, on: :create
  validate :race_overlaps_registered, on: :create

  def duration
    ActionController::Base.helpers.number_with_precision(self[:duration], precision: 2) if self[:duration].present?
  end

  private

  def person_availability
    person = Person.find(person_id)
    return if !person.ongoing_practice?

    errors.add(:person_id, 'has an ongoing practice')
  end

  def person_eligibility
    person = Person.find(person_id)
    trail_id = Race.find(race_id).trail_id

    return if person.finished_practice_on?(trail_id)

    errors.add(:person_id, 'did not finish practice for this trail')
  end

  def race_ongoing_registration
    return if Race.find(race_id).status_NEW?

    errors.add(:race_id, 'no longer accepting registrations')
  end

  def race_overlaps_registered
    registered_runs = Person.find(person_id).registered_runs
    tentative_race = Race.find(race_id)

    registered_runs.each do |run|
      next if !run.race.overlaps?(tentative_race.start, tentative_race.duration)

      errors.add(:race_id, 'overlaps with another registered race')
      break
    end
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :set_person
  before_action :set_run, only: %i[show update]
  before_action :set_races, only: %i[new create]

  def show
  end

  def new
    @run = Run.new
  end

  def create
    @run = @person.runs.create(run_params)

    redirect_to person_path(@person) and return if @run.errors.blank?

    render :new, status: :unprocessable_entity
  end

  def update
    flash[:alert] = 'Cannot update run' if !@run.update(run_params)

    redirect_to person_run_path(@person, @run)
  end

  private

  def set_person
    @person = Person.find(params[:person_id] || run_params[:person_id])
  end

  def set_run
    @run = Run.find(params[:id])
  end

  def set_races
    @races = Race.where(status: :NEW)
  end

  def run_params
    params.require(:run).permit(:person_id, :race_id, :status)
  end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/new.html.erb
<h3>Register to a Race for: <%= @person.name %></h3>


<%= form_with model: [@person, @person.runs.build] do |form| %>
  <div>
    <%= form.label "Select a Race" %>
    <%= form.select :race_id, @races.collect {|race| [race.name, race.id]} %>
  </div>
  <% @run.errors.full_messages.each do |message| %>
    <div class="form_error"><%= message %></div>
  <% end %>
  <div>
    <%= form.submit "Register"%>
  </div>
<% end %>

<%= link_to "Back", person_path(@person) %>

app/views/runs/show.html.erb
<h3><%= image_tag("user_32.png")%> <%= @person.name %>'s Page > <%= @run.race.name %></h3>

<article>
  <b>Runner #<%= @run.id %></b> <%= status_tag(@run.status) %><br>
  <%= link_to "Details", trail_race_path(@run.race.trail, @run.race) %><br><br>

  <% if @run.status_REGISTERED? && @run.race.status_NEW? %>
    <%= form_with model: [@person, @run] do |form| %>
      <%= form.hidden_field :status, value: :DROPPED %>
      <%= form.submit "Drop Race"%>
    <% end %>
    <% if flash[:alert] %>
      <div class="form_error"><%= flash[:alert] %></div>
    <% end %>
  <% end %>

  <% if @run.race.status_FINISHED? %>
    Place: <%= @run.place %> <br>
    Run hours: <%= @run.duration %>
  <% end %>
</article>

<%= link_to "Back", person_path(@person) %>